"""Quantum Digital Signature (QDS) data models and signature container."""

from dataclasses import dataclass, field
from typing import List, Tuple, Dict, Any, Optional
import numpy as np


@dataclass
class SignatureElement:
    """A single quantum signature element representing one teleported signature qubit."""
    qubit_index: int
    state_name: str
    basis_choice: str
    bsm_classical_bits: Tuple[int, int]
    quantum_state_vec: np.ndarray
    reconstructed_density_matrix: Optional[np.ndarray] = None


@dataclass
class QuantumDigitalSignature:
    """Complete Quantum Digital Signature bundle generated by Alice."""
    signer_id: str
    session_id: str
    nonce: str
    message_hash_hex: str
    elements: List[SignatureElement] = field(default_factory=list)
    auth_tag: str = ""
    timestamp: float = 0.0
    
    @property
    def length(self) -> int:
        return len(self.elements)
        
    def to_dict(self) -> Dict[str, Any]:
        return {
            "signer_id": self.signer_id,
            "session_id": self.session_id,
            "nonce": self.nonce,
            "message_hash_hex": self.message_hash_hex,
            "signature_length": self.length,
            "auth_tag": self.auth_tag,
            "timestamp": self.timestamp,
            "elements": [
                {
                    "qubit_index": el.qubit_index,
                    "state_name": el.state_name,
                    "basis_choice": el.basis_choice,
                    "bsm_classical_bits": el.bsm_classical_bits,
                }
                for el in self.elements
            ]
        }
